### ISSUE TITLE
Where is My.h

### ISSUE THREAD

**Issue by eliasstein** [AyamiKaze/Galgame_Project#1]
I'm very bad with my english so sorry for that, i want translate Sadistic blood but Your tool for SystemNNN doesn't contain the file My.h or maybe my problem is other? i'm new at this of hacking and that things.

oh and this tool only extract right? i need repack too, well time to study i think

**Comment by AyamiKaze** [comment]
> I'm very bad with my english so sorry for that, i want translate Sadistic blood but Your tool for SystemNNN doesn't contain the file My.h or maybe my problem is other? i'm new at this of hacking and that things.
> 
> oh and this tool only extract right? i need repack too, well time to study i think

only extract for this tool.
For repack, you can use other tool ,or https://github.com/AyamiKaze/GalgameNote/blob/main/SystemNNN_Hook_Tuts/SystemNNN%E4%B8%AD%E6%96%87%E5%8C%96%E7%AE%80%E8%AE%B0%E2%80%94%E2%80%94%E5%9F%BA%E4%BA%8E%E6%BA%90%E7%A0%81%E7%9A%84%E5%8A%A8%E6%80%81%E5%88%86%E6%9E%90.md
